### ISSUE TITLE
PCB layer sequence?

### ISSUE THREAD

**Issue by JonnyHaystack** [ploopyco/classic-trackball#25]
Hi, I'm not sure how to put in the layer stackup/sequence to get the main PCB manufactured from JLCPCB.

![image](https://user-images.githubusercontent.com/1266473/138296341-7c213823-c65b-476f-bcb7-eba9295b7df7.png)

Could you advise on this, and maybe put something in the wiki [Appendix A](https://github.com/ploopyco/classic-trackball/wiki/Appendix-A%3A-Printed-circuit-boards) about it?

Thanks

**Comment by cyberhuman** [comment]
Hey! Have you find the solution?

**Comment by gbrnt** [comment]
The files we have are:
* Base.apr
* Base.EXTREP
* Base.G1
* Base.G2
* Base.GBL
* Base.GBO
* Base.GBS
* Base.GD1
* Base.GM2
* Base.GTL
* Bse.GTO
* Base.GTP
* Base.GTS
* Base-macro.APR_LIB

Looking at [this site](https://www.vse.com/blog/2022/03/08/gerber-file-names/) it says:
- APR: Aperture file
- GTL: Board top layer
- GTB: Board bottom layer
- G1, G2, etc.: Inner layers
- GP1, GP2, etc.: Power and ground plane layers

So JLCPCB's layer names:
- L1 (Top Layer) -> Base.GTL
- L2 (Inner layer 1) -> Base.G1
- L3 (Inner layer 3) -> Base.G2
- L4 (Bottom layer) -> Base.GTB

I'm not familiar with Gerber files so not sure what the rest are.

**Comment by TheWerle** [comment]
![image](https://github.com/ploopyco/classic-trackball/assets/159328578/b61e6e25-3b02-48d0-8e6c-f07d43696546)
In general G=Gerber, B=Bottom, T=Top

GTO/GBO - O= "Overlay" aka silkscreen
GTS/GBS = S=Soldermask, a negative image to define exposed copper
GTP - P=Paste, solder paste stencil layer for automated assembly.  No bottom paste was included because there's no bottom surface-mounted components
GM2 = M = Mechanical CAD layers, in this case the board outline and cutouts

I recommend downloaded Pentalogix ViewMate gerber viewer, always good to review your Gerber outputs and it helps make the filetypes a bit more intuitive.

**Comment by ploopyco** [comment]
Closing; we can't advise on your relationship with your board house.
