### ISSUE TITLE
Thumb trackball

### ISSUE THREAD

**Issue by pianohacker** [ploopyco/classic-trackball#6]
If I were motivated to customize both the enclosure and the PCB, how hard would it be to make a thumb trackball version of this? (Something like the MX Ergo.) I’m thinking that the electronics and firmware might be reusable, with some modifications to the PCB and plastic. Thoughts?

**Comment by ploopyco** [comment]
Hm. Interesting. Not sure I can declare how difficult that would be. If there are four buttons and a trackball with a single sensor, then the firmware should be completely reusable.

The electronics could be pretty similar, too. I imagine that the PMW3360 sensor would sit on the vertical board instead of the base board, since the sensor would probably have to sit at an angle.

The enclosure would be completely different. I don't think it'd be worth it to reuse my enclosure. Probably best to just start from scratch.
